apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-app
  labels:
    app: boardgame-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame-app
  template:
    metadata:
      labels:
        app: boardgame-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: boardgame-app
        image: manavpamnani06/boardgame-app:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-app
  labels:
    app: boardgame-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: boardgame-app